litespeedtech/lsquic

- CMakeLists.txt
- test/unittests/CMakeLists.txt
This addresses the MSVC detection aspect of issue #10.
> cmake: use MSVC variable instead of trying to detect

- src/liblsquic/lshpack.c
> Include vc_compat.h in lshpack.c to fix Windows compilation

- CMakeLists.txt
- src/liblsquic/lsquic_chsk_stream.c
- src/liblsquic/lsquic_frame_reader.c
> Fix or disable new compiler warnings in gcc 6+ and 7+

- CONTRIBUTORS.txt
- EXAMPLES.txt
- test/http_client.c
- test/prog.c
- test/prog.h
- test/test_common.c
- test/test_common.h
The client now can automatically determine the ipadress of an url given in -H or -s
The standard ip version is IPv4. To make the client use IPv6 use the -v flag
Known limitations:
The -v flag needs to be entered before -s in order to work
The client successfully retrieves an IPv6 adress but I could not test wether it can actually connect since I do not have an IPv6 connection.
The same PR as DNS resolution but in one commit now.
> Added DNS Resolution feature to the client.

- CMakeLists.txt
/home/zhangchi09/develop/lsquic-client/test/prog.c:19:26: fatal error: event2/event.h: No such file or directory
compilation terminated.
CMakeFiles/http_client.dir/build.make:86: recipe for target 'CMakeFiles/http_client.dir/test/prog.c.o' failed
make[2]: *** [CMakeFiles/http_client.dir/test/prog on.c.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/http_client.dir/all' failed
make[1]: *** [CMakeFiles/http_client.dir/all] Error 2
Makefile:94: recipe for target 'all' failed
make: *** [all] Error 2
To fix build error on MAC
> [BUGFIX] Fix libevent build error on Darwin

- tools/bench/lsqb.sh
I have added a script that enables the sample client program `http_client` to benchmark QUIC implementations. The script also includes options for benchmarking with common HTTP benchmarking tools (`curl`, `ab`, `h2load`).
> 201901181200 benchmark tool

- src/liblsquic/lsquic_handshake.c
- src/liblsquic/lsquic_handshake.h
This version does not build on AppVeyor because some of the `zero_rtt` structs have empty arrays. This branch removes the empty arrays and uses local variable pointers in the serialization functions.
> [BUILDFIX] Replace empty arrays in zero_rtt structs with local var ptrs

- include/lsquic_types.h
On Alpine Linux, `<sys/types.h>` is not included by default, meaning compilation will fail as e.g. `ssize_t` is undefined. This just makes that include explicit.
For reference see [lsquic-alpine](https://github.com/omarroth/lsquic-alpine/blob/master/APKBUILD).
> Add explicit include for musl

- CMakeLists.txt
if not add this link flag, it will report errors as below:
ld: warning: directory not found for option '-L/usr/local/lib/Debug'
Undefined symbols for architecture x86_64:
"___asan_alloca_poison", referenced from:
_send_headers_ietf in liblsquic.a(lsquic_stream.o)
_qeh_write_headers in liblsquic.a(lsquic_qenc_hdl.o)
_lsquic_qhkdf_expand in liblsquic.a(lsquic_hkdf.o)
"___asan_allocas_unpoison", referenced from:
_send_headers_ietf in liblsquic.a(lsquic_stream.o)
_qeh_write_headers in liblsquic.a(lsquic_qenc_hdl.o)
_lsquic_qhkdf_expand in liblsquic.a(lsquic_hkdf.o)
"___asan_handle_no_return", referenced from:
_main in echo_client.o
_read_stdin in echo_client.o
_prog_sport_cant_send in prog.o
_send_unsent in prog.o
_sport_new in test_common.o
_send_packets_one_by_one in test_common.o …
> fix link issue when use cmake generate xcode project and run http_client

- CMakeLists.txt
- src/liblsquic/lsquic_parse_ietf_v1.c
Adds support for Android Cmake.
Two primary changes:
1. Supressed test compilation for Android ... `lsquic/test` requires libevent and it is not included by default in android NDK. So added an option `-DTESTS=NO` to suppress test compilation. The test suppression is useful even for linux/win when someone wants to just generate the libs. `-TESTS=NO` works on all platforms.
2. `CMakeLists.txt` for Android toolchain.
3. clang (used by android ndk) gives error for unsigned ... signed comparison and I have added a couple of typecasts in one c code file.
Tested with `android-ndk-r21b` for both debug/release. Compilation command used:
```
$ cd lsquic
$ cmake -DTESTS=NO -DBORINGSSL_DIR=../boringssl -DCMAKE_TOOLCHAIN_FILE=$NDK/build/cmake/android.toolchain.cmake -DANDROID_ABI=armeabi-v7a  . #Debug …
```
> Android support

- CMakeLists.txt
With lsquic cmake you can specify BORINGSSL_LIB and BORINGSSL_INCLUDE paths separately, but it has a small glitch currently. This PR fixes it.
Relevant other [discussion](https://github.com/litespeedtech/lsquic/issues/133#issuecomment-630257700).
> fix for BORINGSSL_LIB and BORINGSSL_INCLUDE paths with cmake

- bin/test_common.c
- include/lsquic.h
- src/liblsquic/lsquic_enc_sess_ietf.c
- src/liblsquic/lsquic_engine.c
- src/liblsquic/lsquic_engine_public.h
- src/liblsquic/lsquic_full_conn_ietf.c
- src/liblsquic/lsquic_mini_conn_ietf.c
Under connection migration scenarios (ex. mobile client moving from LTE to WiFi) or intra-machine topology changes (ex. count of running server instances) in order to ensure stable packet steering there must be information in the connection ID to determine target machine + software server instance.
This patch allows the application to embed such information.
> Connection ID Steering

- CMakeLists.txt
- src/liblsquic/CMakeLists.txt
This adds a CMake install target, such that something like:
```
cmake -DCMAKE_INSTALL_PREFIX=install -DBORINGSSL_DIR=$BORINGSSL -Bbuild -S.
cmake --build build --target install
```
Builds and installs liblsquic as follows:
```
% tree install
install
├── include
│   └── lsquic
│       ├── lsquic.h
│       ├── lsquic_types.h
│       └── lsxpack_header.h
└── lib
└── liblsquic.a
```
I am using that on my (playground) setup, and thought I could share it. Feel free to just close that PR if that's not relevant for you :+1:.
> Add CMake install target

- bin/test_common.c
- bin/test_common.h
- docs/apiref.rst
- include/lsquic.h
- src/liblsquic/lsquic_conn.c
- src/liblsquic/lsquic_conn.h
- src/liblsquic/lsquic_enc_sess_ietf.c
- src/liblsquic/lsquic_engine.c
- src/liblsquic/lsquic_full_conn.c
- src/liblsquic/lsquic_full_conn_ietf.c
- src/liblsquic/lsquic_handshake.c
> this trivial patch enables the batching of packets out into a persistent buffer per connection, for cleaner more efficient GSO.
> 
> currently there is no way to relate the peer_ctx back to a connection inside the pmi_allocate callback, so the best you can do is a pool of packet buffers. This can lead to ~40+ unique packet buffers being passed via sendmsg into the kernel and just as many unique copies.
> 
> or one could construct a contiguous buffer of all packets for GSO within the ea_packets_out at the expense of all those copies.
> 
> and all is complicated further by using io_uring given the asynchronous sendmsg completions.
> 
> this patch relies on the assumption of sequence. That for a given connection, the sequence in which packet buffers are requested from pmi_allocate matches …
> GSO-Friendly Packet Memory

- docs/tutorial.rst
- src/liblsquic/lsquic_enc_sess.h
- src/liblsquic/lsquic_enc_sess_ietf.c
- src/liblsquic/lsquic_engine.c
- src/liblsquic/lsquic_full_conn.h
- src/liblsquic/lsquic_full_conn_ietf.c
Extending the get_sst_ctx callback to support setting SSL contexts on the client side similar to the server implementation.
> Support get_ssl_ctx callback for client

- include/lsquic.h
- src/liblsquic/lsquic_full_conn.c
- src/liblsquic/lsquic_full_conn_ietf.c
Support new lsquic_stream_if callback on_conncloseframe_received() to notify application of CONNECTION_CLOSE frame
> Notification callback on CONNECTION_CLOSE frame

- src/liblsquic/lsquic_handshake.c
Problem:
We are using other quic library which scid length is larger than 16B, and we want to change it with lsquic. But I found that lots of client which create new connection with SICD( means 0RTT) will be PRST by lsquic, and cannot establish connection.
Reason:
Lsquic send PRST but not REJ to those client which create with scid(means 0RTT) but  scid length not equal 16B, and these client won't retry, which means that these client will never connect with new server with quic. 
Solution:
If SCID length is larger than 16B, lsquic truncate it, and then determine_rtt will return 1RTT, which means send REJ to client.
> Make other quic library which scid length is larger than 16B can update to lsquic

- src/liblsquic/lsquic_full_conn.c
- src/liblsquic/lsquic_full_conn_ietf.c
Full connection should be closed after CONNECTION_CLOSE frame in.
Issue: https://github.com/litespeedtech/lsquic/issues/281
> Fix: connection may not be closed timely when CONNECTION_CLOSE frame in

- src/liblsquic/lsquic_handshake.c
stk never be inserted to shi_ctx, so we don't need try to delete it.
> m) do not try to delete stk from shi_ctx

- src/liblsquic/lsquic_full_conn_ietf.c
Use printf format specifier macros for platform independent printing of the uint64_t type. See https://en.cppreference.com/w/c/types/integer for more info.
> Use C99 format specifiers to properly print uint64_t

- src/liblsquic/lsquic_ietf.h
IETF QUIC v1(RFC9000)  specified RFC9001(<https://datatracker.ietf.org/doc/html/rfc9001>)   in  section 23 References.
RFC9001 specified  secret key and nonce in  section5.8 .  the value was the same as draft-ietf-quic-tls-33.
> IETF QUIC v1(RFC9000) Retry Packet Integrity use draft-ietf-quic-tls-33 (or RFC9001)

- README.md
- include/lsquic.h
RFC9001: QUIC transport parameters are carried in a TLS extension.
Different versions of QUIC might define a different method for negotiating transport configuration.
h3: quic_transport_parameters(0x39)
REF ISSUE: https://github.com/litespeedtech/lsquic/issues/345
> update boringssl version info to support h3

- src/liblsquic/lsquic_mini_conn.c
#Reproduce
step1: PC1 quic client request normally and save 0rtt resumption info to file quic_0rtt.info
step2: PC2 quic client request with large early data(>10pkts,  20KB) with quic_0rtt.info
expect: step2 handshake successful with 1RTT
result: step2 handshake failed
cause： lsquic drop all new packets, include Full CHLO, when mc_n_deferred >= MINI_CONN_MAX_DEFERRED(10).
> m) fix: handshake may failed if client send too many early data

- CMakeLists.txt
FIND_LIBRARY will fail if boringssl didn't get build yet, so the
following cmake build rule doesn't work:
add_subdirectory(third_party/boringssl)
set(BORINGSSL_LIB ${CMAKE_CURRENT_BINARY_DIR}/third_party/boringssl)
add_subdirectory(third_party/lsquic)
The patch fixed it by allow setting BORINGSSL_LIB_foo explicitly,
e.g.,
add_subdirectory(third_party/boringssl)
set(BORINGSSL_LIB_ssl ssl)
set(BORINGSSL_LIB_crypto crypto)
set(BORINGSSL_LIB_decrepit decrepit)
add_subdirectory(third_party/lsquic)
> Make it easier to include boringssl and lsquic via add_subdirectory()

- src/liblsquic/lsquic_full_conn_ietf.c
I've been experimenting with lsquic's DATAGRAM support recently and hit a snag. In an application that is sending only DATAGRAM frames (no streams), I found that calling [lsquic_conn_want_datagram_write](https://lsquic.readthedocs.io/en/latest/apiref.html#c.lsquic_conn_want_datagram_write) did not result in lsquic raising an [on_dg_write](https://lsquic.readthedocs.io/en/latest/apiref.html#c.lsquic_stream_if.on_dg_write) callback to my application when I next tried to process the connection(s).
I found that if I had DATAGRAM frames ready to transmit immediately when the handshake completed, then the library worked and issued me those callbacks. However, if the handshake completed before any data was ready to be sent, then I could not send any DATAGRAM frames at all.
This pull request is …
> Tick connection on want_datagram_write

- CMakeLists.txt
- src/liblsquic/CMakeLists.txt
- src/liblsquic/lsquic-config.cmake
You were doing the first half of this already, just not the second half needed to actually use this :)
Does not perform transitive link to boringssl though.
> Add an installed CMake config.

- CMakeLists.txt
It's apparently unused, and it's not installed by vcpkg.
> Remove refs to decrepit boringssl library.

- src/liblsquic/CMakeLists.txt
FindPerl.cmake populates PERL_EXECUTABLE.
Corresponding fix also required in ls-qpack: https://github.com/litespeedtech/ls-qpack/pull/42
Found when submitting lsquic to vcpkg.
> Fix consistency in use of Perl.

- CMakeLists.txt
Windows installs are broken without it. Alternative is to inline the important parts
in lsquic.h which is probably better.
For some reason this was removed in the 3.1.0 release commit, my earlier PR's had it. ( see https://github.com/litespeedtech/lsquic/commit/a74702c630e108125e71898398737baec8f02238#comments )
> Add back vc_compat.h header install.

- src/liblsquic/lsquic_packet_out.c
1) lsquic_packet_out_chop_regan assert(adj) may failed.
2) packet's regen size MUST minus frame size which has been pad over.
> m) Fix: chop regen api may assert fail

- src/liblsquic/lsquic_rechist.c
- src/liblsquic/lsquic_rechist.h
- tests/test_rechist.c
Added test case produces a corrupt rechist. The rechist grows and then is
emptied, then a rechist is produced that is nominally empty (rh_n_used == 0)
but has a circular list in rh_elems.
lsquic_rechist_received: insert before done
0x7ffe65ce75a0: cutoff 9 l. acked 12087061905995 masks 1 alloced 4 used 1 max ranges 0 head 0
(0)[9-9] (0)[9-9] (0)[9-9] (0)[9-9] (0)[9-9] (0)[9-9] (0)[9-9]
test_rechist: /tmp/lsquic/src/liblsquic/lsquic_rechist.c:272: rechist_test_sanity: Assertion `rechist->rh_n_used == n_elems' failed.
> Test case and fix for lsquic rechist list problem

- src/liblsquic/lsquic_hash.h
Hi,
I experienced problems when trying to link lsquic with a cpp project.
Adding this extern "C" fixes the issue.
> link fix when using lsquic in a cpp project

- src/liblsquic/lsquic_engine.c
`lsquic_handshake.h` is included twice in `lsquic_engine.c`.
> Remove redundant include

- src/liblsquic/lsquic_full_conn.c
- src/liblsquic/lsquic_full_conn_ietf.c
Description:
- Error may occur while processing ack frame, e.g. poison packet was acked by hostile attack. and then conn is supposed to be aborted, shortly but not immediately;
- if ack frame processing failed while calling lsquic_engine_packet_in, and IFC_HAVE_SAVED_ACK had been set, then saved ack frame will be processed while ticking connection before it is aborted, that may lead to assert failure;
Solution:
- close connection if neccessary before processing ack while ci_tick.
> [fix] assertion failure if poison packet was acked

- tests/test_rechist.c
error: 'for' loop initial declarations are only allowed in C99 mode
> m) Fix: compile test_rechist error and format

- src/liblsquic/lsquic_enc_sess_ietf.c
- src/liblsquic/lsquic_engine.c
- src/liblsquic/lsquic_mm.c
- src/liblsquic/lsquic_mm.h
[Reproduce]
http_client POST large body request to http_server, like:
http_client -H quic.test.com -s $SERVER_ADDR:$SERVER_PORT -p /1KB_char.txt -M POST -P /test/quic-data/html/10KB_char.txt -o version=h3 -n 100 -r 50000000 -R 500 -w 10 -K
[Notes]
RFC5116 AEAD Section 5.1
An authentication tag with a length of 16 octets (128bits) is used.
RFC9001 QUIC-TLS Section 5.3
These cipher suites have a 16-byte authentication tag and produce an output 16 bytes larger than their input.
@litespeedtech Please check this PR, thanks!
> m) Fix: packet_in pool memory leak

- src/liblsquic/lsquic_http1x_if.c
[Reproduce]
http_client send GET/POST request with large headers(val_len > 256Bytes) to http_server, like:
http_client -H quic.test.com -s $SERVER_ADDR:$SERVER_PORT -p "/test/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" -o version=h3 -n 1 -r 100 -R 100
@litespeedtech @gwanglst  Please check this PR, thank you!
> m) Fix: http1x memory leak

- src/liblsquic/lsquic_stream.c
[BUG]
http_server might not send  MAX_STREAMS to increase  limits if client cancel stream prematurely.
[PROTOCOL]
RFC9000 3.5.
A STOP_SENDING frame requests that the receiving endpoint send a RESET_STREAM frame. An endpoint that receives a STOP_SENDING frame MUST send a RESET_STREAM frame if the stream is in the "Ready" or "Send" state. If the stream is in the "Data Sent" state, the endpoint MAY defer sending the RESET_STREAM frame until the packets containing outstanding data are acknowledged or declared lost. If any outstanding data is declared lost, the endpoint SHOULD send a RESET_STREAM frame instead of retransmitting the data.
RFC9000 19.4. RESET_Frames
An endpoint uses a RESET_STREAM frame (type=0x04) to abruptly terminate the sending part of a stream.
[Reproduce] 
Request big file …
> Fix: http_server might not send  MAX_STREAMS to increase  limits if client cancel stream prematurely

- src/liblsquic/lsquic_enc_sess_ietf.c
- src/liblsquic/lsquic_handshake.c
same memory leak issue in gquic50 with #426 , which may cause continuous memory growth.
another suspicious memory leak when packet_in->pi_data is own.
> fix memory leak when gquic50 decrypt packet

- src/liblsquic/lsquic_handshake.c
There is a memory leak in scfg_key because the key and lsc_scfg are copied inside shi_insert since Release 3.1.2, and no one will release it after that.
For the same reason, scfg_ptr is never equal to enpub->enp_server_config->lsc_scfg after shi_insert.
> fix memory leak when gquic handshake

- src/liblsquic/lsquic_full_conn_ietf.c
1) iquic on_new_conn only be called after handshake_ok, keep same with gquic.
2) on_conn_closed only be called by ci_destroy
optimize commit: https://github.com/litespeedtech/lsquic/commit/850b0a3d100b2abe89cf054a9f8d13054fac34a3
> m) optimize new conn logic

- src/liblsquic/lsquic_enc_sess_ietf.c
Re: https://bugs.chromium.org/p/boringssl/issues/detail?id=558#c1
Since a recent change that puts boringssl's public API more in line with OpenSSL, there is a constness mismatch in the function type of `copy_X509` that may cause compilation failures.
As it turns out, the function we are using there (`sk_deep_copy`) is documented as a private API. We could use `sk_X509_deep_copy`, casting away the const in `copy_X509` to increment the refcount, but the existing function `X509_chain_up_ref` does exactly what we want here.
> Fix: do not use private openssl function to copy cert chain

- src/liblsquic/lsquic_mini_conn.c
[Reproduction]
Assuming the total data volume of the handshake crypto stream in http_client is 1000 bytes, during actual transmission, we repeatedly send data from the range [256, 1000] while excluding the range [0, 256), creating a handshake hole scenario. As a result, http_server triggers a core dump due to an assert failure.
> Fix handshake hole assert failed and coredump

- src/liblsquic/lsquic_full_conn_ietf.c
After some time without activity (only keepalive), the ping frame was send in loop.
> Fix spam of ping network frames.

- bin/http_server.c
Currently both the [response delay in http_server](https://github.com/litespeedtech/lsquic/blob/0b9f50b5f0f2ce2968eaa68294db7af69abe88fc/bin/http_server.c#L1780) and the [log timestamp format](https://github.com/litespeedtech/lsquic/blob/0b9f50b5f0f2ce2968eaa68294db7af69abe88fc/bin/prog.c#L157) use the character `y` for their command line option. This PR renames the response delay option from y to Y to fix that  currently the log timestamp format is shadowed by the response delay and can not be specified for http_server. In my opinion it makes more sense to rename the response delay instead of the log timestamp format as this way the parameter can be kept consistent with other binaries in `/bin`. As the [option string in http_server](https://github.com/litespeedtech/lsquic/blob/0b9f50b5f0f …
> Rename http_server response delay to Y to not shadow log timestamp format

- src/liblsquic/lsquic_full_conn_ietf.c
https://github.com/litespeedtech/lsquic/issues/518.
The function `process_max_stream_data_frame()` returns an error if it detects that the corresponding stream has not been created, causing LSQUIC to close the connection.
1. If this stream is **initiated by peer**, the local side should **create the receiving part of the stream** and transition to the Recv state upon receiving a max_stream_data frame (similar to how process_stream_frame() handles it).
2. If this stream is **initiated by local side**, the local side should consider it as a **connection error of type STREAM_STATE_ERROR**.
We submitted the solution according to RFC9000.
> Fixes #518: lsquic compliance with RFC 9000 for MAX_STREAM_DATA frame

- src/liblsquic/lsquic_send_ctl.c
PR(#511) was previously submitted to address this issue, but there might be some cases that were not fully considered. 
To ensure that the lsquic assert problem does not occur here again, this commit provides a more comprehensive solution.
> Fix: alternative solution for issue that split lost packet api may cause regen assert fail

- include/lsquic.h
- src/liblsquic/lsquic_engine.c
- src/liblsquic/lsquic_full_conn_ietf.c
- src/liblsquic/lsquic_hcso_writer.c
- src/liblsquic/lsquic_hcso_writer.h
- src/liblsquic/lsquic_stream.c
- src/liblsquic/lsquic_stream.h
Both Firefox and Chrome supported. Per my observation currently suppoted WebTransport version is https://datatracker.ietf.org/doc/draft-ietf-webtrans-http3/05/
closes #386
> WebTransport server support for client initiated bidi streams added.

- .cirrus.yml
- CMakeLists.txt
- appveyor-linux.yml
- appveyor-windows.cmd
- appveyor-windows.yml
- src/liblsquic/lsquic_crypto.c
The sha256, lshkdf_* and lsquic_c255_* apis use libcrypto apis calls that are unique to boringssl.  We should fix those up to use API's that are common between boringssl and openssl so that lsquic can be built with either library.
This is in pursuit of #113 so that, eventually openssl can be used as TLS backend for lsquic.
> Fix up sha256, lshkdf_* and lsquic_c255_* apis to be compatible with openssl

- Dockerfile
- bin/http_client.c
While trying to build a local lsquic docker image for interop testing, I noticed a few problems.
1) I had added a space in the cmake directive for LIBSSL_LIB_ssl which
doesn't need to be there, but both the LIBSSL_LIB_ssl and
LIBSSL_LIB_crypto macros don't need to be specified anymore as the
cmake infrastructure detects those properly, so lets just remove
them.
2) The http_client.c file fails to build in the docker image:
8.492 In file included from /src/lsquic/bin/http_client.c:52: 8.492 /src/lsquic/bin/../src/liblsquic/lsquic_stream.h:87:25: error: field 'shf_frame_type' has incomplete type
8.492    87 |     enum hq_frame_type  shf_frame_type;
8.492       |                         ^~~~~~~~~~~~~~
8.492 /src/lsquic/bin/../src/liblsquic/lsquic_stream.h:101:33: error: field …
> Fix Docker image builds
